<center><img src="img/quest/aml-logo.png" width="600"/>
    
***

<center>Lecture 8</center>

***

<center>Model Evaluation <br> + <br>Learning with Imbalanced Data</center>

***

<center>15 April 2024<center>
<center>Rahman Peimankar<center>

# Agenda
* Important binary and multi-class classification metrics

    1. Confusion matrix
    2. Sensitivity & specificity
    3. Receiver Operating Characteristic (ROC)
    4. Area Under the Curve (AUC)
    
* Other metrics
* Implementation examples
* Metrics for regression models
* Imbalanced data (basic approaches) 

    1. Random undersampling
    2. Random oversampling
    3. Synthetic Minority Oversampling Technique (SMOTE)

# Recap of Last Week

# From a Raw Table of Data to a Decision Tree

Here, we want to create a tree that uses **chest pain**, **good blood circulation** and **blocked artery status** to predict whether or not a patient has **heart disease**.

<div>
<center>
<img src="img/quest/Qimage-11-lecture7.jpg" width="1050"/>
</div>

<font color='black'> The first thing we want to know is whether **chest pain**, **good blood circulation** and **blocked artery status** should be at the very top of our tree. (<font color='red'> **The Root Node**<font color='black'>)

<div>
<center>
<img src="img/quest/Qimage-34-lecture7.jpg" width="900"/>
</div>

# Automatic Feature Selection Using Decison Tree

Now, imagine if **Chest Pain** never gave us a reduction in impurity score ... <br>
If this were the case, we would never use Chest Pain to separate the patients, and Chest Pain would not be part of our tree.
    
<div>
<center>
<img src="img/quest/Qimage-45-lecture7.jpg" width="500"/>
</div>

* Even though we have data for **Chest Pain**, it is not part of our tree any more.
* <font color='green'>This is a type of automatic feature selection.

* We could have also created large thereshold for impurity so that the reduction in impurity have to be large enough to be considered. 
* This results in simpler trees that are not **overfitted**.

# Missing Data in Decison Trees

If overall "yes" occured more times than "no", we could put "yes" here!
<div>
<center>
<img src="img/quest/Qimage-48-lecture7.png" width="500"/>
</div>

* Alternatively, we could find another column that has the highest correlation with blocked arteries and use that as a guide.
* In this case, Chest Pain and Blocked Arteries are often very similar.
    
<div>
<center>
<img src="img/quest/Qimage-49-lecture7.png" width="700"/>
</div>

If we had numeric data (weight) instead of Blocked Artery data, we could replace this missing value with the mean or median!<br>
Alternatively, we could find another column that has the highest correlation with weight...

<div>
<center>
<table><tr>
<td>
    
<font size='5'>
    
<img src="img/quest/Qimage-50-lecture7.png" width="500"/>

</td>
<td>

<font size='5'>
        
<img src="img/quest/Qimage-51-lecture7.jpg" width="500"/>
    
</td>
</tr></table>

# Regression Trees

In this case, fitting a straight line to the data will not be very useful! <font color='red'>**Why?** 
<div>
<center>
<img src="img/quest/Qimage-59-lecture7.jpg" width="500"/>
</div> 

We start by asking if the **Dosages** is less than **14.5**.
<div>
<center>
<img src="img/quest/Qimage-61-lecture7.jpg" width="950"/>
</div>

If the **Dosage >= 14.5** and **Dosage >= 29**, then we are talking about these 4 observations, which have the **Average Drug effectiveness** equal to **2.5%**.
<div>
<center>
<img src="img/quest/Qimage-62-lecture7.jpg" width="950"/>
</div>

If the **Dosage >= 14.5**, **Dosage < 29** and **Dosage >= 23.5** then we are talking about these 5 observations, which have the **Average Drug effectiveness** equal to **52.8%**.
<div>
<center>
<img src="img/quest/Qimage-63-lecture7.jpg" width="950"/>
</div>

Lastly, if the **Dosage >= 14.5**, **Dosage < 29** and **Dosage < 23.5** then we are talking about these 4  observations, which have the **Average Drug effectiveness** equal to **100%**.
<div>
<center>
<img src="img/quest/Qimage-64-lecture7.jpg" width="650"/>
</div>

# Random Forests

1. Create a "boorstrapped" dataset
2. Create a Decision Tree

* Create a decision tree using the bootstrapped dataset.
* But only use a random subset of variables (**columns**) at each step.

# Out-Of-Bag Dataset

We run the Out-Of-Bag sample through all of the other trees that were built without it...
<div>
<img src="img/quest/Qimage-80-lecture7.jpg" width="900"/>
    
* 2 trees say **NO** to Out-Of-Bag sample and 1 says **YES**
* So the the Out-Of-Bag sample classified correctly as **NO**

<font size="25"><center>Model Evaluation

# Binary Classification Metrics

Imagine that we have a dataset to predict **Heart Disease** using different features (variables).
<div>
<center>
<img src="img/quest/Qimage-1.jpg" width="650"/>
</div>

To achieve this we could use:
<div>
<center>
<table><tr>
<td>
    
**Logistic Regression**
    
<img src="img/quest/Qimage-2.jpg" width="500"/>
    
</td>
<td>
    
**K-Nearest Neigbors**
    
<img src="img/quest/Qimage-3.jpg" width="500"/>
    
</td>
    
<td>
    
**Random Forest**
    
<img src="img/quest/Qimage-4.jpg" width="700"/>
    
</td>
</tr></table>
    
Or any other methods available!
   

* But how do we decide which one works best?

# 1. Confusion Matrix

* We divide the dataset into **Training Data** and **Testing Data**.
* Then we **train all of the methods** that we have with the **training data**.
* And then **test each method** on the **testing data**.

Now we need to summarize how each method performs on the testing data.<br>
<font color='green'>One way to do this is by creating the **Confsion Matrix** for each method.<br>


<div>
<center>
<table><tr>
<td>    
<img src="img/quest/Qimage-5.jpg" width="800"/>   
</td>
<td>
<img src="img/quest/Qimage-6.jpg" width="800"/> 
</td>   
<td>   
<img src="img/quest/Qimage-7.jpg" width="800"/> 
</td>
</tr></table>  

* The rows in a Confusion Matrix corresponds to what the machine learning algorithm predicted.
* The columns correspond to the known truth.

## 1-1. True Positives

* The top left corner contains **True Positives**.
* These are the patients that *had heart disease* that were correctly identified by the algorithm. 

<div>
<center>
<img src="img/quest/Qimage-8.jpg" width="850"/>
</div>

##  1-2. True Negatives

* The **True Negatives** are in the bottom right-hand corner.
* These are the patients that *did not have heat disease* that were correctly identified by the algorithm.
<div>
<center>
<img src="img/quest/Qimage-9.jpg" width="850"/>
</div>

##  1-3. False Negatives

* The bottom left-hand corner contains **False Negatives**.
* **False Negatives** are when a patient has a heart disease, but the algorithm said they didn't.
<div>
<center>
<img src="img/quest/Qimage-10.jpg" width="850"/>
</div>

## 1-4. False Positives

* The top right-hand corner contains the **False Positives**.
* **False Positives** are patients that do not have heart disease, but the algorithm says they.
<div>
<center>
<img src="img/quest/Qimage-11.jpg" width="850"/>
</div>

# Quiz 1
Suppose your classification model predicted true for a class which actual value was false. Then this is a

A) False Positive <br>
B) False Negative <br>
C) True Positive <br>
D) True Negative <br>

Please answer here: https://PollEv.com/multiple_choice_polls/dFsL4CYvLLSa54GSRP2dT/respond

## 1-5. How to Interpret the Confusion Matrix

* The numbers along the diagonal (the <font color='green'>Green Boxes)<font color='black'> tell us how many times the samples were correctly classified.
* The numbers *not* on the diagonal (the <font color='red'>Red Boxes)<font color='black'> are samples the algorithm messed up.
<div>
<center>
<img src="img/quest/Qimage-12.jpg" width="750"/>
</div>

Now we can compare the **Random Forest's Confusion Matrix** to the **Confusion Matrix** we get when we use **K-Nearest Neighbors**.

<div>
<center>
<img src="img/quest/Qimage-13.jpg" width="1050"/>
</div>

<div>
<center>
<img src="img/quest/Qimage-14.jpg" width="1050"/>
</div>

* **K-Nearest Neigbors** was worse than the **Random Forest** at predicting patients *with* Heart Disease (**107** vs **142**).
* And worse at predicting patients *without* Heart Disease (**79** vs **110**).

## 1-6. When We Need More Than Confusion Matrix!

<div>
<center>
<img src="img/quest/Qimage-15.jpg" width="950"/>
</div>

* These two **Confusion Matrices** are very similar and make it hard to choose which machine learning method is a better fit for this data.
* We will talk about more sophisticated metrices, such as **Sensitivity, Specificity, ROC** and **AUC**, that can help us make a decision in such cases later on!

# 2. Sensitivity & Specificity

<div>
<center>
<img src="img/quest/Qimage-16.jpg" width="850"/>
</div>

## 2-1. Sensitivity (Se)

**Sensitivity** tells us what percentage of patients **_with_** heart disease were correctly identified.
<div>
<center>
<img src="img/quest/Qimage-17.jpg" width="850"/>
</div>

**Sensitivity**$ = \frac{True\,Positives}{True\,Positives + False\,Negatives}$

## 2-2. Specificity (Sp)

**Specificity** tells us what percentage of patients **_without_** heart disease were correctly identified.
<div>
<center>
<img src="img/quest/Qimage-18.jpg" width="750"/>
</div>

**Specificity**$ = \frac{True\,Negatives}{True\,Negatives + False\,Positives}$

## 2-3. Let's Calculate Se & Sp

<div>
<center>
<img src="img/quest/Qimage-15.jpg" width="950"/>
</div>

### Logistic Regression Model

<div>
<center>
<img src="img/quest/Qimage-19.jpg" width="650"/>
</div>

**Sensitivity**$ = \frac{True\,Positives}{True\,Positives + False\,Negatives} = \frac{139}{139 + 32} = 0.81$

**Specificity**$ = \frac{True\,Negatives}{True\,Negatives + False\,Positives} = \frac{112}{112 + 20} = 0.85$

* **Sensitivity** tells us that **81%** of the people **_with_** Heart Disease were correctly identified by the model.
* **Specificity** tells us that **85%** of the people **_without_** Heart Disease were correctly identified by the model.

### Random Forest Model

<div>
<center>
<img src="img/quest/Qimage-20.jpg" width="650"/>
</div>

**Sensitivity**$ = \frac{True\,Positives}{True\,Positives + False\,Negatives} = \frac{142}{142 + 29} = 0.83$

**Specificity**$ = \frac{True\,Negatives}{True\,Negatives + False\,Positives} = \frac{110}{110 + 22} = 0.83$

### Logistic Regression or Random Forest?

<div>

<table><tr>
<td>
    
* **Sensitivity** = 0.83
* **Specificity** = 0.83
    
<img src="img/quest/Qimage-21.jpg" width="600"/>
    
</td>
<td>
    
* **Sensitivity** = 0.81
* **Specificity** = 0.85
    
<img src="img/quest/Qimage-22.jpg" width="600"/>
    
</td>
</tr></table>

* **Sensitivity** tells us that the **Random Forest** is slightly better at correctly classifying *positives* cases.
* **Specificity** tells us that the **Logistic Regression** is slightly better at correctly classifying *negatives* cases.

# Quiz 2
With the help of a confusion matrix, we can compute

A) Sensitivity <br>
B) Precision<br>
C) Accuracy<br>
D) All of the above<br>

Please answer here: https://PollEv.com/multiple_choice_polls/gqCnGIy2nOu8fS7DRHQLW/respond

# 3. Multi Class Confusion Matrix

<div>
<center>
<img src="img/quest/Qimage-23.jpg" width="650"/>
</div>

* There are no single vale for **Se** and **Sp** that work for the entire matrix.
* Instead we calculate a different **Se** and **Sp** for each fault class.

# 4. Multi Class Sensitivity

<div>
<center>
<img src="img/quest/Qimage-24.jpg" width="650"/>
</div>

$Sensitivity_{Fault 1} = \frac{True\,Positives_{Fault 1}}{True\,Positives_{Fault 1} + False\,Negatives_{Fault 1}} = \frac{12}{12 + (112 + 83)} = 0.06$
* **Sensitivity** tells us that only **6%** of Fault 1 class were correctly identified as Fault 1 class.

# 5. Multi Class Specificity

<div>
<center>
<img src="img/quest/Qimage-25.jpg" width="850"/>
</div>


$Specificity{Fault 1} = \frac{True\,Negatives_{Fault 1}}{True\,Negatives_{Fault 1} + False\,Positives_{Fault 1}} = \frac{(23+77+92+17)}{(23+77+92+17) + (102 + 93)} = 0.52$
* **Specificity** for Fault 1 tells us that **52%** of *other* fault classes (Fault 2 and Fault 3) were correctly classified.
* <font color='red'>**Practice**: calculate Se and Sp for other classes (Fault 2 and Fault 3)!

# 6. Receiver Operating Characteristic (ROC)

<div>
<center>
<img src="img/quest/Qimage-26.jpg" width="650"/>
</div>

* The <font color='blue'> blue dots <font color='black'> represent <font color='blue'> obese <font color='black'> mice ...
* The <font color='red'> red dots <font color='black'> represent mice that are <font color='red'> not obese.

* Now let's fit a Logistic Regression curve to the data
<div>
<center>
<img src="img/quest/Qimage-27.jpg" width="550"/>
</div>
    


* The y-axis is converted to the probability that a mouse <font color='blue'> is obese.
<div>
<center>
<img src="img/quest/Qimage-28.jpg" width="550"/>
</div>

The curve would tell us that there is a **high** probability that the mouse <font color='blue'> is obese.
<div>
<center>
<img src="img/quest/Qimage-29.jpg" width="550"/>
</div>

For this mouse, there is a **low** probability that the mouse <font color='blue'> is obese.
<div>
<center>
<img src="img/quest/Qimage-30.jpg" width="550"/>
</div>

## 6-1. Turn Probabilities into Classification

* One way to classify mice is to set a threshold (cutoff) at **0.5**.
<div>
<center>
<img src="img/quest/Qimage-31.jpg" width="550"/>
</div>

Let's evaluate the effectiveness of this Logistic Regression with the classification threshold set to **0.5**!
<div>
<center>
<img src="img/quest/Qimage-32.jpg" width="550"/>
</div>

<div>
<center>
<img src="img/quest/Qimage-33.jpg" width="550"/>
</div>
    
* Now we can calculate **Se** and **Sp** to evaluate this Logistic Regression at **threshold = 0.5**

## 6-2. New Threshold

* Since we are at the middle ot an epidemi, let assume that we would like to predict infected vs not infected individuals instead of obesity!
* Here, it is absolutely essential to correctly classify *every* sample infected in order to minimize the risk of an outbreak... 
* So, we could lower the threshold to **0.1**.

<div>
<center>
<img src="img/quest/Qimage-34.jpg" width="450"/>
</div>

* Let's look at the Confusion Matrix for this threshold!
<div>
<center>
<img src="img/quest/Qimage-35.jpg" width="450"/>
</div>

* On the other hand, lowering the threshold results in more **False Positives**. 

* What if we set the threshold higher e.g. **0.9**!

<div>
<center>
<img src="img/quest/Qimage-36.jpg" width="450"/>
</div>

* With this data, the higher threshold does abetter job classifying samples.

<div>
<center>
<img src="img/quest/Qimage-37.jpg" width="550"/>
</div>

## 6-3. How do We Determine The Best Threshold?

* We do not need to test every single threshold.
* Some thresholds result in the exact same confusion matrix.

But even if we made one confusion matrix for each threshold, it would result in a confusingly large number of confusion matrix!! 

<div>
<center>
<img src="img/quest/Qimage-38.jpg" width="850"/>
</div>

## 6-4. Why ROC?

* **Receiver Operating Characteristic (ROC)** provides a simple way to summarize all of the information.

<div>

<table><tr>
<td>
    
<img src="img/quest/Qimage-39.jpg" width="550"/>
    
</td>
<td>
    
<img src="img/quest/Qimage-40.jpg" width="550"/>
    
</td>
</tr></table>

* The y-axis shows the **True Positive Rate**, which is the same thing as **Sensitivity**.
<center>True Positive Rate = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives}$</center>

* The x-axis shows the **False Positive Rate**, which is the same thing as **1 - Specificity**.
<center>False Positive Rate = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives}$</center>

* To get a better sense of how the **ROC** works, let's draw one from start o finish using our example data.
* We will start by using a threshold that classifies *all* of the samples as <font color='blue'> obese <font color='black'>...
<div>
<center>
<img src="img/quest/Qimage-41.jpg" width="850"/>
</div>

**True Positive Rate** = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives} = \frac{4}{4 + 0} = 1$
* This means that every single <font color='blue'>obese <font color='black'>sample was *correctly* classified.

**False Positive Rate** = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives} = \frac{4}{4 + 0} = 1$
* This means that every single sample that was <font color='red'>not obese <font color='black'>was *incorrectly* classified as <font color='blue'>obese<font color='black'>.

* A point at (1,1) means that even though we correctly classified **all** of the <font color='blue'>obese <font color='black'>samples, we *incorrectly* classified **all** of the samples that were <font color='red'>not obese<font color='black'>.
* This <font color='green'> green diagonla line <font color='black'>shows where the **True Positive Rate = Fasle Positive Rate**
<div>
<center>
<img src="img/quest/Qimage-42.jpg" width="650"/>
</div>

* Let's change the threshold to increase it.
* Assume that we get the below Confusion Matrix.

<div>
<center>
<img src="img/quest/Qimage-43.jpg" width="550"/>
</div>

* **True Positive Rate** = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives} = \frac{4}{4 + 0} = 1$
* **False Positive Rate** = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives} = \frac{3}{3 + 1} = 0.75$
<div>
<center>
<img src="img/quest/Qimage-44.jpg" width="400"/>
</div>

* Let's increase the threshold further!

<div>
<center>
<img src="img/quest/Qimage-45.jpg" width="700"/>
</div>

* **True Positive Rate** = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives} = \frac{4}{4 + 0} = 1$
* **False Positive Rate** = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives} = \frac{2}{2 + 2} = 0.5$

<div>
<center>
<img src="img/quest/Qimage-46.jpg" width="400"/>
</div>

* Let's increase the threshold again!

<div>
<center>
<img src="img/quest/Qimage-47.jpg" width="700"/>
</div>

* **True Positive Rate** = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives} = \frac{3}{3 + 1} = 0.75$
* **False Positive Rate** = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives} = \frac{1}{1 + 3} = 0.25$

<div>
<center>
<img src="img/quest/Qimage-48.jpg" width="400"/>
</div>

* Let's increase the threshold again!!

<div>
<center>
<img src="img/quest/Qimage-49.jpg" width="700"/>
</div>

* **True Positive Rate** = Sensitivity = $\frac{True\, Positives}{True\, Positives\, +\, False\, Negatives} = \frac{3}{3 + 1} = 0.75$
* **False Positive Rate** = 1 - Specificity = $\frac{False\, Positives}{False\, Positives\, +\, True\, Negatives} = \frac{0}{0 + 4} = 0$

<div>
<center>
<img src="img/quest/Qimage-50.jpg" width="400"/>
</div>

* This threshold resulted in no **False Positives**.

* Let's increase the threshold and plot the points! 

<div>
<center>
<img src="img/quest/Qimage-51.jpg" width="400"/>
</div>

* If we increase the threshold to 1, it classifies all of the samples as <font color='red'>not obese <font color='black'>. 
    
<div>

<table><tr>
<td>
    
<img src="img/quest/Qimage-52.jpg" width="350"/>
    
</td>
<td>
    
<img src="img/quest/Qimage-53.jpg" width="350"/>
    
</td>
</tr></table>


## 6-5. ROC Graph 

* Let's connect the dots, which gives us the ROC graph.
* The ROC graph summarizes all of the confusion matrices that each threshold produced.

<div>
<center>
<img src="img/quest/Qimage-54.jpg" width="500"/>
</div>
    
* **Exercise**: What is/are the optimal thresholds? 

# 7. Area Under the Curve (AUC)

* The **AUC** is equal to **0.9** here.

<div>
<center>
<img src="img/quest/Qimage-55.jpg" width="400"/>
</div>

* The **AUC** makes it easy to compare one **ROC** curve to another.

<div>
<center>
<img src="img/quest/Qimage-56.jpg" width="400"/>
</div>

# 8. Other Metrics

* There are other metrics that attempt to do the same thing!

Precision = $\frac{True\, Positives}{True\, Positives\, +\, False\, Positives}$

* **Precision** is the proportion of positive results that were correctly classified.

<div>
<center>
<img src="img/quest/Qimage-57.jpg" width="600"/>
</div>

* If there were lots of samples that were <font color='red'>not obese <font color='black'>relative to the number of <font color='blue'>obese <font color='black'>samples, then **Precision** might be more useful than the **False Positive Rate**.
    
* This is because **Precision** does not include the number of **True Negatives** in its calculation, and is not effected by the imbalance.
    
<div>
<center>
<img src="img/quest/Qimage-58.jpg" width="400"/>
</div>

## 8-1. The Zoo

<div>
<center>
<img src="img/quest/Qimage-59.jpg" width="6800"/>
</div>

https://en.wikipedia.org/wiki/Sensitivity_and_specificity

# 9. Implementation Examples

In [35]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

data = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, stratify=data.target, random_state=0)

lr = LogisticRegression().fit(X_train, y_train)
y_pred = lr.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(lr.score(X_test, y_test))
print('#'*60)
print(classification_report(y_test, y_pred, digits=2))
47/53

[[48  5]
 [ 5 85]]
0.9300699300699301
############################################################
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        53
           1       0.94      0.94      0.94        90

    accuracy                           0.93       143
   macro avg       0.93      0.93      0.93       143
weighted avg       0.93      0.93      0.93       143



0.8867924528301887

In [37]:
y_pred_thresh = lr.predict_proba(X_test)[:, 1] > 0.95
print(classification_report(y_test, y_pred_thresh))
print('#'*60)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.68      1.00      0.81        53
           1       1.00      0.72      0.84        90

    accuracy                           0.83       143
   macro avg       0.84      0.86      0.82       143
weighted avg       0.88      0.83      0.83       143

############################################################
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        53
           1       0.94      0.94      0.94        90

    accuracy                           0.93       143
   macro avg       0.93      0.93      0.93       143
weighted avg       0.93      0.93      0.93       143



In [1]:
from sklearn.metrics import roc_curve
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# Please train a SVM (with default params except gamma=0.05) and a Random Forest model using the same Breast Cancer Dataset. 
# Then, plot the ROC curves of both models in a single figure and compare them. Finally, calculate AUC-ROC using "roc_auc_score" for both models and compare them. 
# You may also check the documnetations of the different functions mentioned here on scikit-learn to learn more about them.

# YOUR CODE HERE


https://www.biostat.wisc.edu/~page/rocpr.pdf

## 9-1. Multi Class Confucion Matrix Implementation

In [17]:
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

digits = load_digits()
# data is between 0 and 16
X_train, X_test, y_train, y_test = train_test_split(digits.data / 16., digits.target, random_state=0)

lr = LogisticRegression(multi_class='ovr').fit(X_train, y_train)
rf = RandomForestClassifier().fit(X_train, y_train)
pred = lr.predict(X_test)
# pred_rf = rf.predict(X_test)
lr_auc = roc_auc_score(y_test, lr.predict_proba(X_test), multi_class='ovo')
rf_auc = roc_auc_score(y_test, rf.predict_proba(X_test), multi_class='ovo')
print("Accuracy: {:.3f}".format(accuracy_score(y_test, pred)))
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(lr_auc)
print(rf_auc)

Accuracy: 0.962
Confusion matrix:
[[37  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  1  1  0  0  0]
 [ 0  0 44  0  0  0  0  0  0  0]
 [ 0  0  0 43  0  0  0  0  1  1]
 [ 0  0  0  0 37  0  0  1  0  0]
 [ 0  0  0  0  0 47  0  0  0  1]
 [ 0  1  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  2  0  0 46  0  0]
 [ 0  3  1  0  0  1  0  1 42  0]
 [ 0  0  0  0  0  2  0  0  0 45]]
0.9981863080889705
0.999356661407736


In [18]:
print(classification_report(y_test, pred))
print(classification_report(y_test, rf.predict(X_test)))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.95      0.93        43
           2       0.98      1.00      0.99        44
           3       1.00      0.96      0.98        45
           4       0.95      0.97      0.96        38
           5       0.92      0.98      0.95        48
           6       0.98      0.98      0.98        52
           7       0.96      0.96      0.96        48
           8       0.98      0.88      0.92        48
           9       0.96      0.96      0.96        47

    accuracy                           0.96       450
   macro avg       0.96      0.96      0.96       450
weighted avg       0.96      0.96      0.96       450

              precision    recall  f1-score   support

           0       0.97      1.00      0.99        37
           1       0.95      0.98      0.97        43
           2       1.00      0.95      0.98        44
           3       0.94 

# 10. Metrics for Regression Models

Build-in standard metrics:

* $R^2$  : easy to understand scale
* MSE : easy to relate to input
* Mean absolute error, median absolute error: more robust

https://scikit-learn.org/stable/modules/model_evaluation.html 

* Mean asolute percentage error (MAPE = $\frac{100}{n}\sum_{i=1}^n|\frac{y-\hat{y}}{y}|$): Absolute vs Relative 

# Quiz 3
Which metric is not used for evaluating classification models?

A) AUC ROC score <br>
B) Accuracy<br>
C) Mean absolute error<br>
D) Prcision<br>

Please answer here: https://PollEv.com/multiple_choice_polls/OlVAGTMG5bEbnlvhDrWxV/respond

<font size="25"><center>Learning with Imbalanced Data

# 11. Imbalanced Data

* All data is imbalanced
* Detect rare events

# 11-1. Mammography Data

In [38]:
from sklearn.datasets import fetch_openml
# mammography https://www.openml.org/d/310
data = fetch_openml('mammography')

In [39]:
import numpy as np
X, y = data.data, data.target
X.shape

(11183, 6)

In [21]:
y = (y.astype(np.int) + 1) // 2
np.bincount(y)


array([10923,   260], dtype=int64)

### Fit a Model on This Mammography Data

In [28]:
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=0)

scores = cross_validate(LogisticRegression(),
                        X_train, y_train, cv=10,
                        scoring=('roc_auc', 'average_precision'))

scores['test_roc_auc'].mean(), scores['test_average_precision'].mean()


(0.9202523350276881, 0.6335760292641773)

# 11-2. Basic Approaches

Change data:

    1. Add samples
    2. Remove samples

# 11-3. Imbalance-Learn
* https://imbalanced-learn.org/stable/
* !pip install -U imbalanced-learn
* An extension to scikit-learn API

### Sampler

To resample a data sets, each sampler implements:

   * data_resampled, targets_resampled = obj.resample(data, targets)

Fitting and sampling can also be done in one step:

   * data_resampled, targets_resampled = obj.fit_resample(data, targets)

# 11-4. Random Undersampling

* conda install -c conda-forge imbalanced-learn
* !pip install -U imbalanced-learn

In [40]:
!pip install -U imbalanced-learn

In [30]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(replacement=False)
X_train_subsample, y_train_subsample = rus.fit_resample(X_train, y_train)
print('X_train: {}'.format(X_train.shape))
print('y_train: {}'.format(np.bincount(y_train)))
print('X_train_undersample: {}'.format(X_train_subsample.shape))
print('y_train_undersample: {}'.format(np.bincount(y_train_subsample)))


X_train: (8387, 6)
y_train: [8192  195]
X_train_undersample: (390, 6)
y_train_undersample: [195 195]


### Random Undersampling Pipeline

In [31]:
from sklearn.linear_model import LogisticRegressionCV
from imblearn.pipeline import make_pipeline as make_imb_pipeline
undersample_pipe = make_imb_pipeline(RandomUnderSampler(), LogisticRegressionCV())
scores = cross_validate(undersample_pipe, X_train, y_train, cv=10, scoring=('roc_auc', 'average_precision'))
scores['test_roc_auc'].mean(), scores['test_average_precision'].mean()

(0.9190187632934744, 0.5522954893068112)

# 11-5. Random Oversampling

In [32]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_train_oversample, y_train_oversample = ros.fit_resample(X_train, y_train)
print('X_train: {}'.format(X_train.shape))
print('y_train: {}'.format(np.bincount(y_train)))
print('X_train_oversample: {}'.format(X_train_oversample.shape))
print('y_train_oversample: {}'.format(np.bincount(y_train_oversample)))

X_train: (8387, 6)
y_train: [8192  195]
X_train_oversample: (16384, 6)
y_train_oversample: [8192 8192]


### Random Oversampling Pipeline

In [33]:
oversample_pipe = make_imb_pipeline(RandomOverSampler(), LogisticRegression())
scores = cross_validate(oversample_pipe, X_train, y_train, cv=10, scoring=('roc_auc', 'average_precision'))
scores['test_roc_auc'].mean(), scores['test_average_precision'].mean()

(0.916433587094691, 0.5801303188497744)

# 11-6. Synthetic Minority Oversampling Technique (SMOTE)

* SMOTE is a technique that generates new observations by interpolating between observations in the dataset.<br>
* For a given observation $x_i$, a new (synthetic) observation is generated by interpolating between one of the k-nearest neighbors, $x_{zi}$.<br>
<center>$x_{new} = x_i + λ(x_{zi}−x_i)$
    
* $\lambda$ is a random number in the range [0,1].
* This interpolation will create a sample on the line between $x_i$ and $x_{zi}$.  

<div>
<center>
<img src="img/quest/Qimage-62.jpg" width="500"/>
</div>

### Visualization of SMOTE

<div>
<center>
<img src="img/quest/Qimage-64.jpg" width="1200"/>
</div>

### Summary

* Always check roc_auc, look at curves
* Undersampling is very fast and can help!
* SMOTE allows adding new interpolated samples

Please check the link below for more examples and methods:<br>
https://imbalanced-learn.org/stable/index.html

### Implementation of SMOTE

In [3]:
from imblearn.over_sampling import SMOTE
import pandas as pd

# Please implement a SMOTE on the previous example of Logistic Regression using "make_imb_pipeline".

# YOUR CODE HERE

<font size="25"><center>Thank you!